CFM_CONSO_SECTION_COL = 1
CFM_CONSO_CASH_MAIN_TYPE_COL = 2
CFM_CONSO_TYPE_COL = 3
CFM_CONSO_SUB_TYPE_COL = 4

CFM_CONSO_YEAR_START_COL = 9
CFM_CONSO_YEAR_ROW = 3

CFM_CONSO_SHEET_NAME = "Conso"

CFM_CONSO_INTERSTED_SECTION = [
    # "CONSOLIDATED INCOME STATEMENT",
    "CASHFLOW PROJECTION",
    "CASH OUTSTANDING BALANCE",
    # "BALANCE SHEET",
    # "RETAINED EARNINGS STATEMENT",
    # "DIVIDEND PAYMENT",
]

CONSO_12M_SECTION_COL = 1
CONSO_12M_CASH_MAIN_TYPE_COL = 2
CONSO_12M_TYPE_COL = 3
CONSO_12M_SUB_TYPE_COL = 4

CONSO_12M_COMPANY_TYPE = 5

CONSO_12M_YEAR_START_COL = 8
CONSO_12M_YEAR_ROW = 3

CONSO_12M_SHEET_NAME = "Conso_12M"

SUMMARY_REPORT_CASH_BALANCE_SAP_KEY_COL = 0
SUMMARY_REPORT_CASH_BALANCE_SAP_VALUE_COL = 1
SUMMARY_REPORT_CASH_BALANCE_SAP_REPORT_DATE_KEY = "Report as of date"
SUMMARY_REPORT_CASH_BALANCE_SAP_SHEET_NAME = "Cash Balance SAP"

SUMMARY_REPORT_CASH_BALANCE_REPORT_NAME_ROW = 2
SUMMARY_REPORT_CASH_BALANCE_REPORT_GROUP_REPORT_KEY = "By Group Report"
SUMMARY_REPORT_CASH_BALANCE_REPORT_SHEET_NAME = "Cash Balance Report"

SUMMARY_REPORT_INVESTMENT_SHEET_NAME = "Investment"
SUMMARY_REPORT_COUNTERPARTY_LIMIT_SHEET_NAME = "Counterparty Limit"
SUMMARY_REPORT_GRAPH_SHEET_NAME = "Graph"
SUMMARY_REPORT_WORKING_CAP_SHEET_NAME = "Working Cap"
SUMMARY_REPORT_BANK_FACILITY_SHEET = "ST Bank Facility"