# Generated by Django 4.2.1 on 2023-05-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
